CREATE TABLE "users" (
  "id" varchar(128) PRIMARY KEY,
  "display_name" varchar(255),
  "avatar_url" text,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "games" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "max_players" int,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "rooms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int,
  "player1_id" varchar(128),
  "player2_id" varchar(128),
  "status" varchar(50),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "scores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" varchar(128),
  "game_id" int,
  "score" int,
  "played_at" datetime,
  "room_id" int
);

ALTER TABLE "rooms" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "rooms" ADD FOREIGN KEY ("player1_id") REFERENCES "users" ("id");

ALTER TABLE "rooms" ADD FOREIGN KEY ("player2_id") REFERENCES "users" ("id");

ALTER TABLE "scores" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "scores" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "scores" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");
