// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: chinchiro.proto

package chinchiro

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChinchiroService_PlayChinchiro_FullMethodName = "/chinchiro.ChinchiroService/PlayChinchiro"
)

// ChinchiroServiceClient is the client API for ChinchiroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChinchiroServiceClient interface {
	// 双方向ストリーミングRPC
	PlayChinchiro(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChinchiroMessage, ChinchiroMessage], error)
}

type chinchiroServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChinchiroServiceClient(cc grpc.ClientConnInterface) ChinchiroServiceClient {
	return &chinchiroServiceClient{cc}
}

func (c *chinchiroServiceClient) PlayChinchiro(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChinchiroMessage, ChinchiroMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChinchiroService_ServiceDesc.Streams[0], ChinchiroService_PlayChinchiro_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChinchiroMessage, ChinchiroMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChinchiroService_PlayChinchiroClient = grpc.BidiStreamingClient[ChinchiroMessage, ChinchiroMessage]

// ChinchiroServiceServer is the server API for ChinchiroService service.
// All implementations must embed UnimplementedChinchiroServiceServer
// for forward compatibility.
type ChinchiroServiceServer interface {
	// 双方向ストリーミングRPC
	PlayChinchiro(grpc.BidiStreamingServer[ChinchiroMessage, ChinchiroMessage]) error
	mustEmbedUnimplementedChinchiroServiceServer()
}

// UnimplementedChinchiroServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChinchiroServiceServer struct{}

func (UnimplementedChinchiroServiceServer) PlayChinchiro(grpc.BidiStreamingServer[ChinchiroMessage, ChinchiroMessage]) error {
	return status.Errorf(codes.Unimplemented, "method PlayChinchiro not implemented")
}
func (UnimplementedChinchiroServiceServer) mustEmbedUnimplementedChinchiroServiceServer() {}
func (UnimplementedChinchiroServiceServer) testEmbeddedByValue()                          {}

// UnsafeChinchiroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChinchiroServiceServer will
// result in compilation errors.
type UnsafeChinchiroServiceServer interface {
	mustEmbedUnimplementedChinchiroServiceServer()
}

func RegisterChinchiroServiceServer(s grpc.ServiceRegistrar, srv ChinchiroServiceServer) {
	// If the following call pancis, it indicates UnimplementedChinchiroServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChinchiroService_ServiceDesc, srv)
}

func _ChinchiroService_PlayChinchiro_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChinchiroServiceServer).PlayChinchiro(&grpc.GenericServerStream[ChinchiroMessage, ChinchiroMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChinchiroService_PlayChinchiroServer = grpc.BidiStreamingServer[ChinchiroMessage, ChinchiroMessage]

// ChinchiroService_ServiceDesc is the grpc.ServiceDesc for ChinchiroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChinchiroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chinchiro.ChinchiroService",
	HandlerType: (*ChinchiroServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayChinchiro",
			Handler:       _ChinchiroService_PlayChinchiro_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chinchiro.proto",
}
